# -*- coding: utf-8 -*-
"""EDS Practical No.4 .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0bX1y616eJ52VXBNwwP-I9_LzwxroLK
"""

import numpy as np
import pandas as pd

df = pd.read_csv("yelp_reviews.csv")

print(df.head())

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df['stars'].value_counts().sort_index()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df.groupby('stars')[['cool', 'useful', 'funny']].mean()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df['user_id'].value_counts().head(10)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['date'] = pd.to_datetime(df['date'])
result = df['date'].dt.year.value_counts().sort_index()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['word_count'] = df['text'].apply(lambda x: len(x.split()))
result = df.groupby('stars')['word_count'].mean()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df['date'].value_counts().head(5)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df[df['useful'] > 20][['business_id', 'stars', 'useful']].sort_values(by='useful', ascending=False)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df['business_id'].value_counts().head(10)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df[['stars', 'cool', 'useful', 'funny']].corr()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['char_count'] = df['text'].str.len()
result = df.nlargest(5, 'char_count')[['review_id', 'char_count']]
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df[df['stars'] == 1].groupby('business_id').size().sort_values(ascending=False).head(10)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.month
result = df.groupby('month')['stars'].mean()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
top_users = df['user_id'].value_counts().head(5).index
result = df[df['user_id'].isin(top_users)].groupby('user_id')['stars'].mean()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['total_feedback'] = df['cool'] + df['useful'] + df['funny']
result = df[df['total_feedback'] > 50][['review_id', 'total_feedback']].sort_values(by='total_feedback', ascending=False)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
counts = df['business_id'].value_counts()
popular = counts[counts > 10].index
result = df[df['business_id'].isin(popular)].groupby('business_id')['stars'].var().sort_values(ascending=False).head(10)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df.groupby('stars')['business_id'].nunique()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df_filtered = df[df['useful'] > 0].copy()
df_filtered['ratio'] = df_filtered['cool'] / df_filtered['useful']
result = df_filtered.nlargest(10, 'ratio')[['review_id', 'ratio']]
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['date'] = pd.to_datetime(df['date'])
result = df['date'].dt.day_name().value_counts()
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
result = df[df['stars'] == 5].groupby('user_id').size().sort_values(ascending=False).head(5)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['date'] = pd.to_datetime(df['date'])
yearly = df['date'].dt.year.value_counts().sort_index()
result = yearly.pct_change() * 100
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
high_stars = df[df['stars'] >= 4]
stats = high_stars.groupby('business_id').agg({'useful': ['mean', 'count']})
stats.columns = ['avg_useful', 'count']
result = stats[stats['count'] > 5].sort_values(by='avg_useful', ascending=False).head(10)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
active = df['user_id'].value_counts()[df['user_id'].value_counts() > 10].index
volatility = df[df['user_id'].isin(active)].groupby('user_id')[['cool', 'useful', 'funny']].std().mean(axis=1)
result = volatility.sort_values(ascending=False).head(5)
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['date'] = pd.to_datetime(df['date'])
df['month_name'] = df['date'].dt.month_name()
df['total_f'] = df['cool'] + df['useful'] + df['funny']
result = df.groupby('month_name').agg({'stars': 'mean', 'total_f': 'sum', 'review_id': 'count'})
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
df['has_pos'] = df['text'].str.contains('excellent|amazing', case=False)
result = df.groupby('stars')['has_pos'].mean() * 100
print(result)

import pandas as pd
import numpy as np

df = pd.read_csv('yelp.csv')
top_3 = df['business_id'].value_counts().head(3).index
df_top = df[df['business_id'].isin(top_3)].sort_values('date')
result = df_top.groupby(['business_id', 'date'])['useful'].sum().groupby(level=0).cumsum()
print(result.head(20))